CREATE DATABASE IF NOT EXISTS web2;

USE web2;

CREATE TABLE IF NOT EXISTS usr_usuarios(
	usr_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	usr_nome VARCHAR(100) NOT NULL UNIQUE,
	usr_senha CHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS cli_clientes(
	cli_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	cli_nome VARCHAR(100) NOT NULL,
	cli_cpf CHAR(11) NOT NULL UNIQUE,
	cli_nascimento DATETIME NOT NULL,
	cli_sexo CHAR(1) NOT NULL,
	cli_email VARCHAR(100) NOT NULL UNIQUE,
	cli_senha CHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS  pac_pacotes(
	pac_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	pac_nome VARCHAR(100) NOT NULL UNIQUE,
	pac_descricao LONGTEXT NOT NULL,
	pac_url_foto VARCHAR(255) DEFAULT NULL,
	pac_valor DOUBLE NOT NULL
);

INSERT INTO usr_usuarios VALUES (NULL, 'argel', 'e10adc3949ba59abbe56e057f20f883e');
INSERT INTO usr_usuarios VALUES (NULL, 'rafael', 'e10adc3949ba59abbe56e057f20f883e');
