<?php

?>

    <script src="<?=$this->generateURLResouce('bower_components/jquery/dist/jquery.min.js')?>"></script>
    <script src="<?=$this->generateURLResouce('bower_components/bootstrap/dist/js/bootstrap.min.js')?>"></script>
    <script src="<?=$this->generateURLResouce('bower_components/metisMenu/dist/metisMenu.min.js')?>"></script>
    <script src="<?=$this->generateURLResouce('bower_components/raphael/raphael-min.js')?>"></script>
    <script src="<?=$this->generateURLResouce('bower_components/morrisjs/morris.min.js')?>"></script>
    <script src="<?=$this->generateURLResouce('js/morris-data.js')?>"></script>
    <script src="<?=$this->generateURLResouce('dist/js/sb-admin-2.js')?>"></script>
    <script src="<?=$this->generateURLResouce('js/mask.js')?>"></script>
    <script src="<?=$this->generateURLResouce('js/form.js')?>"></script>

</body>

</html>


