<!DOCTYPE html>
<html lang="pt_BR">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>VCV - Agência de Viagens</title>

    <link href="<?=$this->generateURLResouce('bower_components/bootstrap/dist/css/bootstrap.min.css')?>" rel="stylesheet">
    <link href="<?=$this->generateURLResouce('bower_components/metisMenu/dist/metisMenu.min.css')?>" rel="stylesheet">
    <link href="<?=$this->generateURLResouce('dist/css/timeline.css')?>" rel="stylesheet">
    <link href="<?=$this->generateURLResouce('dist/css/sb-admin-2.css')?>" rel="stylesheet">
    <link href="<?=$this->generateURLResouce('bower_components/morrisjs/morris.css')?>" rel="stylesheet">
    <link href="<?=$this->generateURLResouce('bower_components/font-awesome/css/font-awesome.min.css')?>" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$this->generateURL('dashboard/')?>">VCV - Agência de Viagens</a>
            </div>
            
            <ul class="nav navbar-top-links navbar-right">    
                <li>
                    <i class="fa fa-user fa-fw"></i> &nbsp;&nbsp;Bem vindo
                </li>
                <li>
                    <a  href="<?=$this->generateURL('login/logout.php')?>">Sair</a>
                </li>
            </ul>
            
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="<?=$this->generateURL('dashboard/')?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>            
                        <li>
                            <a href="<?=$this->generateURL('pacote/')?>"><i class="fa fa-plane fa-fw"></i>Pacotes</a>
                        </li>
                        <li>
                            <a href="<?=$this->generateURL('cliente/')?>"><i class="fa fa-users fa-fw"></i>Clientes</a>
                        </li>
                        <li>
                            <a href="<?=$this->generateURL('usuario/')?>"><i class="fa fa-cogs fa-fw"></i> Usuários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

