<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Editar Usuário</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    Formulário de Usuário
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-sm-12 col-sm-offset-0">
                            <form id="form-usuario" class='form-horizontal' method="POST" action="<?= $this->generateURL('usuario/alterar.php?id=' . $this->usuario->getId()) ?>">

                                <?php if ($this->hasMensagensErro()): ?>
                                    <?php foreach ($this->getMensagensErro() as $message): ?>
                                        <div class="alert alert-danger"><?= $message ?></div>
                                    <?php endforeach; ?>
                                <?php endif; ?>

                                <?php if ($this->hasMensagensInfo()): ?>
                                    <?php foreach ($this->getMensagensInfo() as $message): ?>
                                        <div class="alert alert-info"><?= $message ?></div>
                                    <?php endforeach; ?>
                                <?php endif; ?>

                                <?php if ($this->hasMensagensSucesso()): ?>
                                    <?php foreach ($this->getMensagensSucesso() as $message): ?>
                                        <div class="alert alert-success"><?= $message ?></div>
                                    <?php endforeach; ?>
                                <?php endif; ?>

                                <div class="form-group">
                                    <label for='nome' class="col-md-3 control-label">Nome de Usuário</label>
                                    <div class='col-md-9 col-sm-12'>
                                        <input class="form-control" readonly id="nome" name="nome" type="text" value="<?= $this->usuario->getNome() ?>">
                                    </div>
                                </div>

                                <div class="form-group">

                                    <label for='senha' class="col-md-3 control-label">Senha</label>
                                    <div class='col-md-9 col-sm-12'>
                                        <input class="form-control" id="senha" name="senha" type="password">
                                        <p class="help-block">Senha deve ter pelo menos 6 caracteres!</p>
                                    </div>
                                </div>

                                <div class='clear'>&nbsp;</div>
                                <div class='form-group'>
                                    <div class='col-md-offset-2 col-md-10 col-sm-offset-0 col-sm-12'>
                                        <button type="submit" class="btn btn-success">Cadastrar</button>
                                        <button type="reset" class="btn btn-info">Limpar os Dados</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
</div>


