<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Adicionar Pacote</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    Formulário de Pacote
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-sm-12 col-sm-offset-0">
                            <form class='form-horizontal' enctype="multipart/form-data" method="POST" action="<?= $this->generateURL('pacote/cadastrar.php') ?>">

                                <?php if ($this->hasMensagensErro()): ?>
                                    <?php foreach ($this->getMensagensErro() as $message): ?>
                                        <div class="alert alert-danger"><?= $message ?></div>
                                    <?php endforeach; ?>
                                <?php endif; ?>

                                <?php if ($this->hasMensagensInfo()): ?>
                                    <?php foreach ($this->getMensagensInfo() as $message): ?>
                                        <div class="alert alert-info"><?= $message ?></div>
                                    <?php endforeach; ?>
                                <?php endif; ?>

                                <?php if ($this->hasMensagensSucesso()): ?>
                                    <?php foreach ($this->getMensagensSucesso() as $message): ?>
                                        <div class="alert alert-success"><?= $message ?></div>
                                    <?php endforeach; ?>
                                <?php endif; ?>

                                <div class="form-group">
                                    <label for='nome' class="col-md-3 control-label">Nome</label>
                                    <div class='col-md-9 col-sm-12'>
                                        <input class="form-control" id="nome" name="nome" type="text" value="<?= $this->pacote->getNome() ?>">
                                    </div>
                                </div>

                                <div class="form-group">

                                    <label for='descricao' class="col-md-3 control-label">Descricao</label>
                                    <div class='col-md-9 col-sm-12'>
                                        <textarea class="form-control" id="descricao" name="descricao" type="text"><?= $this->pacote->getDescricao()?></textarea>
                                    </div>
                                </div>

                                <div class="form-group">

                                    <label for='valor' class="col-md-3 control-label">Valor</label>
                                    <div class='col-md-9 col-sm-12'>
                                        <input class="form-control" id="valor" name="valor" type="text" value="<?= $this->pacote->getValor() ?>">
                                    </div>
                                </div>
                                        
                                <div class="form-group">
                                    <label for="foto" class="col-md-3 control-label">Foto</label>
                                    <div class='col-md-9 col-sm-12'>
                                        <input type="file" id="foto" name="foto" accept="image/*">
                                    </div>
                                </div>

                                <div class='clear'>&nbsp;</div>
                                <div class='form-group'>
                                    <div class='col-md-offset-2 col-md-10 col-sm-offset-0 col-sm-12'>
                                        <button type="submit" class="btn btn-success">Cadastrar</button>
                                        <button type="reset" class="btn btn-info">Limpar os Dados</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
</div>


