<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Pacotes</h1>
        </div>
        </div>
    
    <div class="row">
        <div class="col-lg-12">

            <?php if ($this->hasMensagensErro()): ?>
                <?php foreach ($this->getMensagensErro() as $message): ?>
                    <div class="alert alert-danger"><?= $message ?></div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if ($this->hasMensagensInfo()): ?>
                <?php foreach ($this->getMensagensInfo() as $message): ?>
                    <div class="alert alert-info"><?= $message ?></div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if ($this->hasMensagensSucesso()): ?>
                <?php foreach ($this->getMensagensSucesso() as $message): ?>
                    <div class="alert alert-success"><?= $message ?></div>
                <?php endforeach; ?>
            <?php endif; ?>


            <a href ="<?= $this->generateURL('pacote/cadastrar.php') ?>" class ="btn btn-success">Novo Pacote</a>
            
        </div>
    </div>
    
    <div class="clearfix"><br /><br /><br /></div>
    
    <div class="row">
        <div class="col-lg-12">
            
            <?php if(count($this->pacotes)):?>
                <?php foreach($this->pacotes as $pacote):?>

                    <div class = "col-sm-6 col-md-3 col-xs-12 panel panel-default">
                        <div class="panel-body">

                            <div class = "thumbnail">
                                <a href ="<?= $this->generateURL('pacote/alterar.php?id=' . $pacote->getId()) ?>">
                                    <img class = "img-responsive img-thumbnail"
                                        src = "<?= $this->generateURLImage($pacote->getURLFoto())?>" alt = "<?=$pacote->getNome()?>">
                                </a>
                             </div>

                             <div class = "caption">
                                <h3><?=$pacote->getNome()?></h3>
                                <p>R$ <?=number_format($pacote->getValor(), 2)?></p>

                                <p>
                                     <a href ="<?= $this->generateURL('pacote/alterar.php?id=' . $pacote->getId()) ?>" class ="btn btn-info">
                                         <i class ="fa fa-edit"></i>&nbsp;Editar
                                     </a>

                                     <a href ="<?= $this->generateURL('pacote/deletar.php?id=' . $pacote->getId()) ?>" class ="btn btn-danger delete" data="<?=$pacote->getNome()?>">
                                         <i class ="fa fa-trash"></i>&nbsp;Apagar
                                     </a>
                                </p>

                             </div>
                        </div>
                    </div>

                <?php endforeach;?>
            <?php else:?>
            <h3>Sem pacotes cadastrados!</h3>
            <?php endif;?>
           
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->