<!DOCTYPE html>
<html lang="pt-BR">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>WEB CMS - Login</title>

    <link href="<?=$this->generateURLResouce('bower_components/bootstrap/dist/css/bootstrap.min.css')?>" rel="stylesheet">
    <link href="<?=$this->generateURLResouce('bower_components/metisMenu/dist/metisMenu.min.css')?>" rel="stylesheet">
    <link href="<?=$this->generateURLResouce('dist/css/sb-admin-2.css')?>" rel="stylesheet">
    <link href="<?=$this->generateURLResouce('bower_components/font-awesome/css/font-awesome.min.css')?>" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Painel de Login</h3>
                    </div>
                    <div class="panel-body">
                        
                        <?php if($this->hasMensagensErro()):?>
                            <?php foreach($this->getMensagensErro() as $message):?>
                                <div class="alert alert-danger"><?=$message?></div>
                            <?php endforeach;?>
                        <?php endif;?>

                        <?php if($this->hasMensagensInfo()):?>
                            <?php foreach($this->getMensagensInfo() as $message):?>
                                <div class="alert alert-info"><?=$message?></div>
                            <?php endforeach;?>
                        <?php endif;?>

                        <?php if($this->hasMensagensSucesso()):?>
                            <?php foreach($this->getMensagensSucesso() as $message):?>
                                <div class="alert alert-success"><?=$message?></div>
                            <?php endforeach;?>
                        <?php endif;?>
                                
                        <form id="form-login" role="form" action="<?=$this->generateURL('login/index.php')?>" method="POST">
                            <fieldset>
                                
                                <div class="form-group">
                                    <input class="form-control" id="login" placeholder="Login" name="login" type="text" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" id="senha" placeholder="Senha" name="senha" type="password" value="">
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <input type = "submit" class="btn btn-lg btn-success" value="Login"/>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="<?=$this->generateURLResouce('bower_components/jquery/dist/jquery.min.js')?>"></script>
    <script src="<?=$this->generateURLResouce('bower_components/bootstrap/dist/js/bootstrap.min.js')?>"></script>
    <script src="<?=$this->generateURLResouce('bower_components/metisMenu/dist/metisMenu.min.js')?>"></script>
    <script src="<?=$this->generateURLResouce('dist/js/sb-admin-2.js')?>"></script>
    <script src="<?=$this->generateURLResouce('js/mask.js')?>"></script>
    <script src="<?=$this->generateURLResouce('js/form.js')?>"></script>

</body>

</html>
